version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres-db-voluntario
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: voluntario
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
