server:
  port: 8180
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voluntario?useSSL=false&serverTimezone=@app.timezone
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart.max-file-size: 5MB
    multipart.max-request-size: 5MB
  mail:
    username: ${APP_EMAIL_USER}
    password: ${APP_EMAIL_PWD}
    host: smtp.mailtrap.io
    port: 2525
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
    validate-on-migrate: false
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /v3/api-docs/
    filter: false
    path: /
    doc-expansion: none
logging:
  level:
    root: ERROR
    org:
      hibernate:
        SQL: DEBUG
jwt:
  secret: "123456"
  expires: 43200000
  refresh: 86400000
app:
  timezone: "America/Asuncion"
  login:
    attempts: 5