server:
  port: 8180
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:postgresql://${APP_DB_URL}/${APP_DB_NAME}?useSSL=false&serverTimezone=@app.timezone
    username: ${APP_DB_USER}
    password: ${APP_DB_PWD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart.max-file-size: 5MB
    multipart.max-request-size: 5MB
  mail:
    username: ${APP_EMAIL_USER}
    password: ${APP_EMAIL_PWD}
    host: ${APP_EMAIL_HOST}
    port: ${APP_EMAIL_PORT}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    validate-on-migrate: true
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /v3/api-docs/
    filter: false
    path: /
    doc-expansion: none
logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: ERROR
jwt:
  secret: ${APP_JWT_SECRET}
  expires: ${APP_JWT_REFRESH}
  refresh: ${APP_JWT_REFRESH}
app:
  timezone: ${APP_TIMEZONE}
  login:
    attempts: 5