INSERT INTO "role" ("role") VALUES ('ADMIN');
INSERT INTO "usuario" ("active", "email", "full_name", "ciudad", "join_date", "last_login_date", "non_locked", "password", "updated_at", "user_tipo", "username") VALUES ('1', 'admin@voluntarios.com', 'Administrador', 'San Cristobal', now(), NULL, '1', '$2a$10$8L.jmdP9sgoJWx7TRLS26ulrXVy1i.q3Y3ZW6TzzTOSG.fdh93k3i', NULL, 'V', 'admin');
INSERT INTO "usuario_roles" ("user_id", "roles_id") VALUES ('1', '1');

INSERT INTO "usuario" ("active", "ciudad", "email", "full_name", "join_date", "last_login_date", "non_locked", "password", "updated_at", "user_tipo", "username") VALUES ('1', 'Ciudad del este', 'admin@example.com', 'Datapar S.A', now(), NULL, '1', '$2a$10$8L.jmdP9sgoJWx7TRLS26ulrXVy1i.q3Y3ZW6TzzTOSG.fdh93k3i', NULL, 'O', 'datapar');
INSERT INTO "actividad" ("actividad", "alterado", "creado", "detalle", "inicio", "situacion", "creado_por_id") VALUES ('Limpieza de las calles 1', now(), now(), '<p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p>', now(), 'P', '2');
INSERT INTO "actividad" ("actividad", "alterado", "creado", "detalle", "inicio", "situacion", "creado_por_id") VALUES ('Limpieza de las calles 2', now(), now(), '<p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p>', now(), 'P', '2');
INSERT INTO "actividad" ("actividad", "alterado", "creado", "detalle", "inicio", "situacion", "creado_por_id") VALUES ('Limpieza de las calles 3', now(), now(), '<p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p>', now(), 'P', '2');
INSERT INTO "actividad" ("actividad", "alterado", "creado", "detalle", "inicio", "situacion", "creado_por_id") VALUES ('Limpieza de las calles 4', now(), now(), '<p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p>', now(), 'P', '2');
INSERT INTO "actividad" ("actividad", "alterado", "creado", "detalle", "inicio", "situacion", "creado_por_id") VALUES ('Limpieza de las calles 5', now(), now(), '<p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p>', now(), 'P', '2');
INSERT INTO "actividad" ("actividad", "alterado", "creado", "detalle", "inicio", "situacion", "creado_por_id") VALUES ('Limpieza de las calles 6', now(), now(), '<p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p>', now(), 'P', '2');
INSERT INTO "actividad" ("actividad", "alterado", "creado", "detalle", "inicio", "situacion", "creado_por_id") VALUES ('Limpieza de las calles 7', now(), now(), '<p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p>', now(), 'P', '2');
INSERT INTO "actividad" ("actividad", "alterado", "creado", "detalle", "inicio", "situacion", "creado_por_id") VALUES ('Limpieza de las calles 8', now(), now(), '<p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p>', now(), 'P', '2');                                                                                                                                                                                                                                                                                                                                                                              INSERT INTO "actividad" ("actividad", "alterado", "creado", "detalle", "inicio", "situacion", "creado_por_id") VALUES ('Limpieza de las calles 1', now(), now(), '<p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p>', now(), 'P', '2');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           INSERT INTO "actividad" ("actividad", "alterado", "creado", "detalle", "inicio", "situacion", "creado_por_id") VALUES ('Limpieza de las calles 15', now(), now(), '<p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p><p>Teste Teste Teste Teste </p>', now(), 'P', '2');